### PR TITLE
feat: Introduce simpler dockerfile mode for dmp

### PR DESCRIPTION
**Pull request by rhuss**
See also https://ro14nd.de/simple-dockerfile-mode-dmp

### CODE REVIEW

**Comment by arun-gupta** [comment]
DMP will use this Dockerfile instead of inline configuration?

No change in `mvn install -Pdocker` generating Docker image? There are other scripts that rely upon that command.

**Comment by rhuss** [comment]
Ok, I will check the binding for "install", but otherwise its a full replacement.

**Comment by rhuss** [comment]
Yes, works for me with as before:

```
$ mvn install -Pdocker -Pdocker.repo=rhuss
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building greeting 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ greeting ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/roland/Development/docker/microservices-greeting/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ greeting ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ greeting ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/roland/Development/docker/microservices-greeting/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ greeting ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ greeting ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-war-plugin:2.5:war (default-war) @ greeting ---
[INFO] Packaging webapp
[INFO] Assembling webapp [greeting] in [/Users/roland/Development/docker/microservices-greeting/target/greeting]
[INFO] Processing war project
[INFO] Copying webapp resources [/Users/roland/Development/docker/microservices-greeting/src/main/webapp]
[INFO] Webapp assembled in [145 msecs]
[INFO] Building war: /Users/roland/Development/docker/microservices-greeting/target/greeting.war
[INFO]
[INFO] --- wildfly-swarm-plugin:2018.2.0:package (default) @ greeting ---
Resolving 89 out of 262 artifacts
[INFO] Repackaging .war: /Users/roland/Development/docker/microservices-greeting/target/greeting.war
[INFO] Repackaged .war: /Users/roland/Development/docker/microservices-greeting/target/greeting.war
[INFO]
[INFO] --- docker-maven-plugin:0.25.1:build (docker:build) @ greeting ---
[INFO] Building tar: /Users/roland/Development/docker/microservices-greeting/target/docker/rhuss/greeting/latest/tmp/docker-build.tar
[INFO] DOCKER> [rhuss/greeting:latest]: Created docker-build.tar in 1 second
[INFO] DOCKER> [rhuss/greeting:latest]: Built image sha256:b0c55
[INFO] DOCKER> [rhuss/greeting:latest]: Removed old image sha256:cff50
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ greeting ---
[INFO] Installing /Users/roland/Development/docker/microservices-greeting/target/greeting.war to /Users/roland/.m2/repository/org/aws/samples/compute/greeting/1.0-SNAPSHOT/greeting-1.0-SNAPSHOT.war
[INFO] Installing /Users/roland/Development/docker/microservices-greeting/pom.xml to /Users/roland/.m2/repository/org/aws/samples/compute/greeting/1.0-SNAPSHOT/greeting-1.0-SNAPSHOT.pom
[INFO] Installing /Users/roland/Development/docker/microservices-greeting/target/greeting-swarm.jar to /Users/roland/.m2/repository/org/aws/samples/compute/greeting/1.0-SNAPSHOT/greeting-1.0-SNAPSHOT-swarm.jar
[INFO]
[INFO] --- docker-maven-plugin:0.25.1:push (docker:push) @ greeting ---
[INFO] DOCKER> The push refers to repository [docker.io/rhuss/greeting]
c2c415b78f59: Pushed
148268bf14be: Layer already exists
6a47dae912f7: Layer already exists
00439e7d6354: Layer already exists
a1a8b7f7efac: Layer already exists
341d865c1c22: Layer already exists
61c06e07759a: Layer already exists
bcbe43405751: Layer already exists
e1df5dc88d2c: Layer already exists
[INFO] DOCKER> latest: digest: sha256:7af84a97fc3254f7e263f6d87d184b7fc96aabd931f80f733c57f7dc9d485577 size: 2211
[INFO] DOCKER> Pushed rhuss/greeting:latest in 1 minute and 46 seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:01 min
[INFO] Finished at: 2018-04-13T16:19:18+02:00
[INFO] Final Memory: 48M/521M
[INFO] ------------------------------------------------------------------------
```

**Comment by rhuss** [comment]
If you like that slim approach, I would be happy to send in equivalent PRs for your other projects, too.

**Comment by arun-gupta** [comment]
Let me merge this request but push is still not working. Will open another issue.

Definitely like the slim and clean approach. PRs to other repos would be great.

**Comment by rhuss** [comment]
@arun-gupta found the issue for the push problem, going to make a release now and send PRs for all your repos.

**Pull request merged**
